# Generated by Django 4.2.7 on 2023-12-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcyShop', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
